[project]
name = "dataframe-crossing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipykernel>=7.1.0",
    "jupyterlab>=4.5.0",
    "pandas>=2.3.3",
    "polars>=1.35.2",
]
